server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: ckeun
    password: ck1234

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 272073613504-fh4clhaq352fp6urtobgip53sf70nukd.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 1011607960059313
            client-secret: 0d5f60429001972d6d69e6813ad4d929
            scope:
              - email
              - public_profile
          naver:
            client-id: RdgrGxZqBO4H1ggsuoMX
            client-secret: vmICe4_Ut4
            scope:
              - name
              - email
#              - profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          google:
            user-name-attribute: sub
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response